server:
  port: 18110

spring:
  application:
    name: aom-gateway
  cloud:
    gateway:
      globalcors:
        enabled: false
      routes:
        # 路由1: aom-message 服务 - 优先级高
        - id: aom-message
          uri: http://localhost:18112
          predicates:
            - Path=/aommessage/**
          order: 1

        # 路由2: aom-courses 服务
        - id: aom-courses
          uri: http://localhost:18113
          predicates:
            - Path=/aomcourses/**
          order: 2

        # 路由3: aom-meetings 服务（注意修正路径拼写 mettings -> meetings）
        - id: aom-meetings
          uri: http://localhost:18114
          predicates:
            - Path=/meetings/**
          order: 3

        # 路由4: aom-admin 服务 - 默认路由，优先级最低
        - id: aom-admin
          uri: http://localhost:18111
          predicates:
            - Path=/**
          order: 4


# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

# 日志配置
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
